version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '10:00'
    open-pull-requests-limit: 10
    reviewers:
      - chefjuanpi
    assignees:
      - chefjuanpi
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    target-branch: dev
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      time: '11:00'
    open-pull-requests-limit: 10
    reviewers:
      - chefjuanpi
    assignees:
      - chefjuanpi
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    target-branch: dev
