version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    filters:
      branches:
        only: master
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: yarn
      - run:
        command: yarn run test
        name: Run YARN tests
  release:
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: yarn
      - run:
        command: yarn run semantic-release
        name: Run YARN semantic-release
workflows:
  node_test_and_release:
    jobs:
      - test
      - release:
          requires:
            - test

