type User {
  email: EmailAddress!
  password: String!
  role: Role
  joinDate: String
}

type Role {
  name: String
}

extend type Query {
  users: [User]
  user(email: EmailAddress!): User
  me: User
}

extend type Mutation {
  signIn(email: EmailAddress!, password: String!): String!
  signOut: String!
  signUp(email: EmailAddress!, password: String!, role: String): String
}
